spring.application.name=mini-erp

spring.datasource.url=jdbc:postgresql://localhost:5433/minierp
spring.datasource.username=minierp
spring.datasource.password=minierp

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
