spring.application.name=mini-erp

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:minierp}
spring.datasource.username=${POSTGRES_USER:minierp}
spring.datasource.password=${POSTGRES_PASSWORD:minierp}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
